"""
data_summary
============
Compute correlation summary statistics over the *selected* gene set — the
33 active-everywhere genes that DirectLiNGAM is actually fit on — and write
them to `data_summary.md`.

The point of this table is to characterise the linear-dependence structure
of the data: a correlation matrix that is neither all-zero nor near-rank-one
is the regime where causal *direction* (not just association) is the
interesting question, which motivates LiNGAM over a correlation/covariance
method that could only ever return a Markov equivalence class.

Run:  python data_summary.py
"""

from __future__ import annotations

import os

import numpy as np
from scipy import stats

from causalbench_loader import download_raw_data, preprocess
from lingam_model import select_genes

DATA_DIR  = "./causalbench_data"
NPZ_NAME  = "dataset_k562.npz"
DATASET   = "weissmann_k562"
OUT_PATH  = "data_summary.md"
SEED      = 0


def main() -> None:
    npz_path = os.path.join(DATA_DIR, NPZ_NAME)
    if not os.path.exists(npz_path):
        download_raw_data(DATA_DIR, files=["k562.h5ad"])
        preprocess(DATA_DIR, DATASET)

    sel = select_genes(npz_path, k=None, seed=SEED)
    X = sel.X_obs                       # (n_obs, p) observational, log1p-normalised
    names = sel.gene_names
    n_obs, p = X.shape

    corr = np.corrcoef(X.T)             # (p, p) Pearson
    # Unordered pairs only → strict upper triangle, excluding the unit diagonal.
    iu, ju = np.triu_indices(p, k=1)
    abs_corr = np.abs(corr[iu, ju])     # length p*(p-1)/2
    n_pairs = abs_corr.size

    # Argmax / argmin over the flattened upper triangle, mapped back to genes.
    k_max = int(np.argmax(abs_corr)); k_min = int(np.argmin(abs_corr))
    max_pair = (names[iu[k_max]], names[ju[k_max]])
    min_pair = (names[iu[k_min]], names[ju[k_min]])

    stats_rows = [
        ("Genes in selected set", f"{p}"),
        ("Observational cells", f"{n_obs:,}"),
        ("Unordered gene pairs", f"{n_pairs}"),
        ("Mean |correlation|", f"{abs_corr.mean():.4f}"),
        ("Median |correlation|", f"{np.median(abs_corr):.4f}"),
        ("Std. dev. of |correlation|", f"{abs_corr.std(ddof=1):.4f}"),
        ("Max |correlation|",
         f"{abs_corr[k_max]:.4f}  ({max_pair[0][-5:]} – {max_pair[1][-5:]})"),
        ("Min |correlation|",
         f"{abs_corr[k_min]:.4f}  ({min_pair[0][-5:]} – {min_pair[1][-5:]})"),
        ("Proportion of pairs with |corr| < 0.1",
         f"{(abs_corr < 0.1).mean():.2%}"),
        ("Skewness of |correlation| distribution", f"{stats.skew(abs_corr):+.3f}"),
        ("Excess kurtosis of |correlation| distribution",
         f"{stats.kurtosis(abs_corr):+.3f}"),
    ]

    lines = ["# Data summary — selected gene set (K562, observational)\n"]
    lines.append(
        f"Auto-generated by `data_summary.py` (seed = {SEED}). Statistics are "
        f"computed over the **{p} active-everywhere genes** used in the LiNGAM "
        f"fit, across all **{n_obs:,} observational cells**. \"Correlation\" "
        f"means the Pearson correlation between two genes' log1p-normalised "
        f"expression; pairwise statistics are over the "
        f"{n_pairs} unordered gene pairs.\n"
    )
    lines.append("| Statistic | Value |")
    lines.append("|---|---|")
    for label, value in stats_rows:
        lines.append(f"| {label} | {value} |")
    lines.append("")

    lines.append(
        "**Interpretation.** The selected genes are *pervasively, moderately* "
        f"correlated: every one of the {n_pairs} pairs exceeds "
        f"|corr| = {abs_corr.min():.2f} (none are near-zero), with a median of "
        f"≈ {np.median(abs_corr):.2f} and a mildly right-skewed tail "
        f"(skew {stats.skew(abs_corr):+.2f}) of a few strongly co-varying "
        "pairs reaching ≈ "
        f"{abs_corr.max():.2f}. A dense, near-uniform association structure "
        "like this is exactly where a correlation- or covariance-based method "
        "is least informative: it would declare almost every gene connected to "
        "almost every other, and being symmetric it cannot orient any of those "
        "links (it cannot distinguish i → j from j → i, recovering at best a "
        "Markov equivalence class). LiNGAM instead exploits the "
        "non-Gaussianity of the structural residuals — confirmed in the "
        "exploration figures — to break that symmetry, prune the dense "
        "association graph down to direct effects, and recover a unique causal "
        "ordering.\n"
    )

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT_PATH}  (p={p}, n_obs={n_obs}, pairs={n_pairs})")


if __name__ == "__main__":
    main()
